development:
  password: 059fcd6863f24e0cebfe01ade53ed272
  theme_id: "115714305"
  store: david-meister-sandbox.myshopify.com
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
staging:
  password: 43a2898a25cad17bdd470817a683c4ab
  theme_id: "120145729"
  store: david-meister-staging.myshopify.com
  bucket_size: 40
  refill_rate: 2
